<div class="page-header">
    <h1>Calculator</h1>
</div>

<div id="circle-calculator">

    <h3>Circle</h3>

    <div class="form-group form-inline">
        <label for="radius">Radius</label>
        <input type="text" id="radius" class="form-control" name="radius">
    </div>

    <div class="form-group">
        <button type="button" class="btn btn-primary" id="calculate-circle">Calculate</button>
    </div>

    <div class="form-group form-inline">
        <label for="circle-surface">Surface</label>
        <input type="text" id="circle-surface" class="form-control" name="circle-surface">
    </div>

    <div class="form-group form-inline">
        <label for="circle-circumference">Circumference</label>
        <input type="text" id="circle-circumference" class="form-control" name="circle-circumference">
    </div>

</div>

<hr>

<div id="triangle-calculator">

    <h3>Triangle</h3>

    <div class="form-group form-inline">
        <label for="triangle-a">a</label>
        <input type="text" id="triangle-a" class="form-control" name="triangle-a">
    </div>

    <div class="form-group form-inline">
        <label for="triangle-b">b</label>
        <input type="text" id="triangle-b" class="form-control" name="triangle-b">
    </div>

    <div class="form-group form-inline">
        <label for="triangle-c">a</label>
        <input type="text" id="triangle-c" class="form-control" name="triangle-c">
    </div>

    <div class="form-group">
        <button type="button" class="btn btn-primary" id="calculate-triangle">Calculate</button>
    </div>

    <div class="form-group form-inline">
        <label for="triangle-surface">Surface</label>
        <input type="text" id="triangle-surface" class="form-control" name="triangle-surface">
    </div>

    <div class="form-group form-inline">
        <label for="triangle-circumference">Circumference</label>
        <input type="text" id="triangle-circumference" class="form-control" name="triangle-circumference">
    </div>

</div>


